#!/bin/bash

# Gather statistics
while read -r file
do
    echo "Blaming file: $file"

    temp=$(git blame "$file" | cut -d "(" -f 2 | awk '{ print $1 }')

    names+="$temp "
done

GREEN=$'\e[0;32m'

# process the results
results=$(tr " " "\n" <<<$names | sort | uniq -c)

echo "${GREEN}$results${NC}"
