#!/bin/bash

GREEN="\033[32m"

echo "Parsing files..."

# Gather statistics
while read -r file
do
    git blame "$file" | cut -d "(" -f 2 | awk '{ print $1 }'
done | sort | uniq -c | { var=$(cat); echo -e "$GREEN$var"; }
