#!/bin/bash

BLACK="\033[30m"
RED="\033[31m"
GREEN="\033[32m"
YELLOW="\033[33m"
BLUE="\033[34m"
PINK="\033[35m"
CYAN="\033[36m"
WHITE="\033[37m"
NORMAL="\033[0;39m"

echo "Parsing files..."

# Gather statistics
while read -r file
do
    git blame "$file" | cut -d "(" -f 2 | awk '{ print $1 }'
done | sort | uniq -c | { var=$(cat); echo -e "$GREEN $var"; }
